[package]
name = "libdevice"
version = "0.1.0"
authors = ["junelife"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
drivers = { path = "../drivers" }
hmi = { path = "../hmi" }
lvgl = { path = "../lvgl" }
panic-halt = "0.2.0"

